
from __future__ import annotations
from dengue_rules import RuleOutput
GUIDELINE_CITATIONS={'supportive':'BV Bệnh Nhiệt Đới 2023 – điều trị ngoại trú chủ yếu là điều trị triệu chứng, uống nhiều nước/ORS, paracetamol đơn chất.','avoid':'BV Bệnh Nhiệt Đới 2023 – không dùng Aspirin, Analgin, Ibuprofen trong bối cảnh SXHD.','monitoring':'BV Bệnh Nhiệt Đới 2023 – có dấu hiệu cảnh báo cần theo dõi sát, cân nhắc nhập viện và theo dõi Hct/TC.','escalation':'BV Bệnh Nhiệt Đới 2023 – sốc/XH nặng cần xử trí cấp cứu, truyền dịch theo phác đồ và cân nhắc chế phẩm máu theo tiêu chí.'}
def generate_clinician_suggestions(rule_output: RuleOutput, clinical: dict):
    result={'supportive':[],'monitoring':[],'escalation':[],'contraindication':[]}
    if rule_output.level in {'Có yếu tố gợi ý SXHD','SXHD có dấu hiệu cảnh báo cần chú ý'} and clinical.get('fever_now'):
        result['supportive'].append({'name':'Paracetamol đơn chất','reason':'Chỉ nên dùng paracetamol đơn chất để hạ sốt tham khảo nếu đang sốt.','confirm_before_use':'Xác nhận không vượt tổng liều an toàn và không có chống chỉ định riêng.','citation':GUIDELINE_CITATIONS['supportive'],'confidence':rule_output.data_completeness})
    if rule_output.level in {'Có yếu tố gợi ý SXHD','SXHD có dấu hiệu cảnh báo cần chú ý'} and clinical.get('can_drink'):
        result['supportive'].append({'name':'Bù dịch đường uống / ORS / nước điện giải','reason':'Khuyến khích uống nhiều nước, nước trái cây, Oresol hoặc nước cơm khi điều trị ngoại trú và uống được.','confirm_before_use':'Xác nhận bệnh nhân không nôn liên tục, không sốc, không khó thở, không giảm tri giác.','citation':GUIDELINE_CITATIONS['supportive'],'confidence':rule_output.data_completeness})
    if rule_output.level=='SXHD có dấu hiệu cảnh báo cần chú ý':
        result['monitoring']+=[{'name':'Cân nhắc nhập viện / theo dõi sát','reason':'Có dấu hiệu cảnh báo lâm sàng hoặc pattern Hct/PLT đáng chú ý.','confirm_before_use':'Xác nhận khả năng theo dõi ngoại trú, khoảng cách đến cơ sở y tế, dấu hiệu sinh tồn và huyết động.','citation':GUIDELINE_CITATIONS['monitoring'],'confidence':rule_output.data_completeness},{'name':'Theo dõi Hct/TC và dấu hiệu sinh tồn sát hơn','reason':'Khi có dấu hiệu cảnh báo, cần theo dõi xét nghiệm và sinh hiệu chặt hơn.','confirm_before_use':'Xác nhận thời điểm ngày bệnh, xu hướng xét nghiệm và tình trạng dịch.','citation':GUIDELINE_CITATIONS['monitoring'],'confidence':rule_output.data_completeness}]
    if rule_output.level=='SXHD nặng / cần khám hoặc xử trí khẩn':
        result['escalation']+=[{'name':'Cần bác sĩ đánh giá ngay / xử trí cấp cứu','reason':'Có dấu hiệu đỏ gợi ý sốc, suy hô hấp, xuất huyết nặng hoặc tổn thương tạng.','confirm_before_use':'Xác nhận huyết áp, mạch, tri giác, hô hấp, Hct động, tình trạng chảy máu và cân nặng.','citation':GUIDELINE_CITATIONS['escalation'],'confidence':rule_output.data_completeness},{'name':'Xem xét sơ đồ truyền dịch tinh thể theo guideline (clinician-only)','reason':'Có thể phù hợp khi có dấu hiệu cảnh báo nặng / sốc, nhưng app không tự sinh y lệnh hay liều cố định nếu thiếu dữ liệu.','confirm_before_use':'Cần bác sĩ xác nhận cân nặng, huyết động, tình trạng sốc, nước tiểu và đáp ứng dịch.','citation':GUIDELINE_CITATIONS['escalation'],'confidence':rule_output.data_completeness}]
    result['contraindication']=[{'name':'Không dùng Aspirin','reason':'Tăng nguy cơ xuất huyết.','confirm_before_use':'Luôn tránh trong bối cảnh SXHD nếu không có chỉ định chuyên khoa rất rõ.','citation':GUIDELINE_CITATIONS['avoid'],'confidence':'cao'},{'name':'Không dùng Ibuprofen','reason':'Tăng nguy cơ xuất huyết và biến chứng.','confirm_before_use':'Tránh dùng thường quy trong SXHD.','citation':GUIDELINE_CITATIONS['avoid'],'confidence':'cao'},{'name':'Không dùng Analgin','reason':'Có thể gây xuất huyết / toan máu theo guideline.','confirm_before_use':'Tránh dùng thường quy trong SXHD.','citation':GUIDELINE_CITATIONS['avoid'],'confidence':'cao'},{'name':'Không tự đề xuất corticosteroid hoặc kháng sinh thường quy','reason':'Không phải điều trị chuẩn của SXHD nếu không có chỉ định rõ.','confirm_before_use':'Chỉ cân nhắc khi có đánh giá bác sĩ và bằng chứng chỉ định.','citation':GUIDELINE_CITATIONS['avoid'],'confidence':'cao'}]
    return result
